/**
 * Unit tests for the QRZ Logbook route's parsing and aggregation logic
 * (server/routes/qrz-logbook.js). The route module returns its internals
 * under _qrzLogbook for exactly this purpose — no network involved.
 */

import { describe, expect, it } from 'vitest';

const route = require('./qrz-logbook.js');

function makeApp() {
  const handlers = {};
  const register =
    (method) =>
    (path, ...fns) => {
      handlers[`${method} ${path}`] = fns[fns.length - 1];
    };
  return { get: register('GET'), post: register('POST'), handlers };
}

function makeCtx() {
  return {
    fetch: () => {
      throw new Error('network disabled in tests');
    },
    CONFIG: {},
    APP_VERSION: 'test',
    ROOT_DIR: process.cwd(),
    logDebug: () => {},
    logErrorOnce: () => {},
    writeLimiter: (req, res, next) => next(),
    requireWriteAuth: (req, res, next) => next(),
  };
}

const { parseQrzResponse, parseAdifRecords, aggregateRecords, isConfirmed } = route(makeApp(), makeCtx())._qrzLogbook;

// ─── parseQrzResponse ─────────────────────────────────────────────────────────

describe('parseQrzResponse', () => {
  it('parses simple KEY=VALUE pairs', () => {
    const fields = parseQrzResponse('RESULT=OK&COUNT=42&LOGIDS=1,2,3');
    expect(fields.RESULT).toBe('OK');
    expect(fields.COUNT).toBe('42');
    expect(fields.LOGIDS).toBe('1,2,3');
  });

  it('reassembles HTML-entity-encoded ADIF split apart by & separators', () => {
    // &lt; and &gt; contain '&', which shreds a naive split
    const raw = 'RESULT=OK&ADIF=&lt;call:4&gt;W1AW &lt;gridsquare:4&gt;FN31 &lt;eor&gt;&COUNT=1';
    const fields = parseQrzResponse(raw);
    expect(fields.RESULT).toBe('OK');
    expect(fields.COUNT).toBe('1');
    expect(fields.ADIF).toBe('<call:4>W1AW <gridsquare:4>FN31 <eor>');
  });

  it('decodes percent-encoded values', () => {
    const fields = parseQrzResponse('REASON=invalid%20api%20key');
    expect(fields.REASON).toBe('invalid api key');
  });
});

// ─── parseAdifRecords ─────────────────────────────────────────────────────────

describe('parseAdifRecords', () => {
  it('parses multiple records split by <eor>', () => {
    const adif =
      '<call:4>W1AW <gridsquare:4>FN31 <band:3>20m <eor>' + '<call:5>DL1AB <gridsquare:6>JO62QM <band:3>40m <eor>';
    const records = parseAdifRecords(adif);
    expect(records).toHaveLength(2);
    expect(records[0].CALL).toBe('W1AW');
    expect(records[0].GRIDSQUARE).toBe('FN31');
    expect(records[1].GRIDSQUARE).toBe('JO62QM');
  });

  it('skips the header before <eoh>', () => {
    const adif = 'Generated by QRZ <adif_ver:5>3.1.4 <eoh> <call:4>W1AW <eor>';
    const records = parseAdifRecords(adif);
    expect(records).toHaveLength(1);
    expect(records[0].CALL).toBe('W1AW');
    expect(records[0].ADIF_VER).toBeUndefined();
  });

  it('respects declared field lengths (values containing spaces and brackets)', () => {
    const adif = '<comment:11>hi <there!> <call:4>W1AW <eor>';
    const records = parseAdifRecords(adif);
    expect(records[0].COMMENT).toBe('hi <there!>');
    expect(records[0].CALL).toBe('W1AW');
  });

  it('handles type-annotated fields like <freq:6:N>', () => {
    const records = parseAdifRecords('<freq:6:N>14.074 <call:4>W1AW <eor>');
    expect(records[0].FREQ).toBe('14.074');
  });

  it('returns empty array for empty/missing input', () => {
    expect(parseAdifRecords('')).toEqual([]);
    expect(parseAdifRecords(undefined)).toEqual([]);
  });
});

// ─── isConfirmed ──────────────────────────────────────────────────────────────

describe('isConfirmed', () => {
  it('accepts any confirmation source', () => {
    expect(isConfirmed({ QSL_RCVD: 'Y' })).toBe(true);
    expect(isConfirmed({ LOTW_QSL_RCVD: 'Y' })).toBe(true);
    expect(isConfirmed({ EQSL_QSL_RCVD: 'Y' })).toBe(true);
    expect(isConfirmed({ APP_QRZLOG_STATUS: 'C' })).toBe(true);
  });

  it('rejects unconfirmed QSOs', () => {
    expect(isConfirmed({})).toBe(false);
    expect(isConfirmed({ QSL_RCVD: 'N', LOTW_QSL_RCVD: 'R' })).toBe(false);
  });
});

// ─── aggregateRecords ─────────────────────────────────────────────────────────

describe('aggregateRecords', () => {
  it('aggregates QSOs into 4-char grids with counts, bands, and lastWorked', () => {
    const { grids, summary } = aggregateRecords([
      { GRIDSQUARE: 'FN31pr', BAND: '20M', QSO_DATE: '20250110', LOTW_QSL_RCVD: 'Y' },
      { GRIDSQUARE: 'FN31', BAND: '40m', QSO_DATE: '20260301' },
      { GRIDSQUARE: 'JO62', BAND: '20m', QSO_DATE: '20240815' },
      { GRIDSQUARE: '', BAND: '20m' }, // no grid — counted in totalQsos only
    ]);

    expect(summary.totalQsos).toBe(4);
    expect(summary.qsosWithGrid).toBe(3);
    expect(summary.gridCount).toBe(2);
    expect(summary.confirmedGrids).toBe(1);

    const fn31 = grids.find((g) => g.grid === 'FN31');
    expect(fn31.qsoCount).toBe(2);
    expect(fn31.confirmedCount).toBe(1);
    expect(fn31.bands).toEqual({ '20m': 1, '40m': 1 });
    expect(fn31.lastWorked).toBe('2026-03-01');

    const jo62 = grids.find((g) => g.grid === 'JO62');
    expect(jo62.confirmedCount).toBe(0);
  });

  it('picks the most common state/province and country per grid', () => {
    const { grids } = aggregateRecords([
      { GRIDSQUARE: 'EN81', STATE: 'OH', COUNTRY: 'United States' },
      { GRIDSQUARE: 'EN81', STATE: 'OH', COUNTRY: 'United States' },
      { GRIDSQUARE: 'EN81', STATE: 'MI', COUNTRY: 'United States' },
      { GRIDSQUARE: 'FN03', VE_PROV: 'ON', COUNTRY: 'Canada' }, // legacy province field
      { GRIDSQUARE: 'JO62', COUNTRY: 'Germany' }, // no state — country fallback
      { GRIDSQUARE: 'PM95' }, // no location data at all
    ]);

    expect(grids.find((g) => g.grid === 'EN81')).toMatchObject({ state: 'OH', country: 'United States' });
    expect(grids.find((g) => g.grid === 'FN03')).toMatchObject({ state: 'ON', country: 'Canada' });
    expect(grids.find((g) => g.grid === 'JO62')).toMatchObject({ state: null, country: 'Germany' });
    expect(grids.find((g) => g.grid === 'PM95')).toMatchObject({ state: null, country: null });
  });

  it('collects per-grid QSO details sorted newest-first', () => {
    const { qsosByGrid } = aggregateRecords([
      {
        GRIDSQUARE: 'EN81',
        CALL: 'W1AW',
        QSO_DATE: '20250110',
        TIME_ON: '1423',
        QTH: 'Newington',
        NAME: 'Hiram',
        RST_SENT: '-05',
        RST_RCVD: '-10',
        FREQ: '14.074',
        MODE: 'FT8',
        LOTW_QSL_RCVD: 'Y',
      },
      { GRIDSQUARE: 'EN81', CALL: 'K2XYZ', QSO_DATE: '20260301', TIME_ON: '020530', MODE: 'CW' },
    ]);

    const qsos = qsosByGrid.get('EN81');
    expect(qsos).toHaveLength(2);
    // Newest first
    expect(qsos[0]).toMatchObject({ call: 'K2XYZ', date: '2026-03-01', time: '02:05', confirmed: false });
    expect(qsos[1]).toMatchObject({
      call: 'W1AW',
      date: '2025-01-10',
      time: '14:23',
      city: 'Newington',
      name: 'Hiram',
      rstSent: '-05',
      rstRcvd: '-10',
      freq: '14.074',
      mode: 'FT8',
      confirmed: true,
    });
    // Internal sort key is stripped from the payload
    expect(qsos[0]._sort).toBeUndefined();
  });

  it('rejects malformed grid squares', () => {
    const { summary } = aggregateRecords([
      { GRIDSQUARE: 'ZZ99' }, // Z out of A-R field range
      { GRIDSQUARE: '1234' },
      { GRIDSQUARE: 'F' },
    ]);
    expect(summary.gridCount).toBe(0);
    expect(summary.qsosWithGrid).toBe(0);
  });
});
